### ISSUE TITLE
ZeDMDHD

### ISSUE THREAD

**Issue by uronito** [Nelfe80/RetroBat-Marquee-Manager#4]
Your work is wonderful. I am using it with zedmdhd, would it be possible to speed up the loading of images? since when changing systems or games it is a bit difficult to load the images in zedmdhd. Would it be possible to configure the zedmd part?
On the other hand, would it be possible that closing the application with stop.bat would turn off zedmd?

**Comment by Nelfe80** [comment]
Sorry, I hadn't tested it with zeDMDHD. Glad it works. Concerning the display speed, I haven't found a solution to speed up the display. GIFs display quite well and are fluid. You can try it out. Marquee videos are also transformed into animated GIFs on the fly.
Why kill the process? Because if you do it with stop, it won't work anymore. But in stop, if you want, you can actually kill your process :
:: Vérifier et fermer dmdserver.exe si en cours d'exécution
tasklist | find /I "dmd.exe" > NUL
if not errorlevel 1 taskkill /IM dmd.exe /F

**Comment by uronito** [comment]
Thanks, you're a crack!!!!!!!
